os: osx
sudo: required
language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "6"

install:
  - "npm install"
  - "travis_wait brew cask install unity"

script:
  - "npm test"
  - "npm install -g"

  # Test examples
  - "./example/run-unity.sh"
  - "node ./example/run-unity.js"

after_script:
  - "npm install coveralls && nyc report --reporter=text-lcov | coveralls"
