os: osx
sudo: required
language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "node"
  - "lts/*"
  - "7"
  - "6"

install:
  - "npm install"

script:
  - "npm test"
  - "npm install -g"

after_script:
  - "npm install coveralls && nyc report --reporter=text-lcov | coveralls"
